[project]
name = 'packr'
version = '1.3.0'
description = "Package and optimize Minecraft Resource Packs"
authors = [
    { name = "Soumeh" }
]
dependencies = [
    "Pillow",
    "requests",
]

[tool.setuptools]
packages = [
    'packr'
]

[project.scripts]
principality = "packr.__main__:main"